version: '3.8'

services:
  api:
    build: .
    container_name: healthcare-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Note: Supabase is not included in this docker-compose as we're using an external Supabase instance
  # You would connect to your own Supabase account as specified in the .env file