[project]
name = "diabeteschatbotapi"
version = "0.1.0"
description = ""
authors = [
    {name = "VIBHU SAHU",email = "77403072+VibhuSahu@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
langchain-openai = "^0.3.16"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
